title: Eduardo Cerda-Sánchez Fotografías
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1057348
  brandStrength: 0.125
  rhythmicContrast: 0.4820789
  brandColors:
    - '#000000'
    - '#9d9d9d'
    - '#4b4b4b'
    - '#232323'
    - '#ececec'
  lightness: 0.07706093
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Eduardo Cerda-Sánchez
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.50444
layout_spectrum: 1
